version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - commands:
          install-server-deps:
            description: "Installing server dependencies"
            steps:
              - run: cd reactnd-contacts-server
              - run: npm install
          install-ui-deps:
            description: "Installing UI dependencies"
            steps:
              - run: cd reactnd-contacts-complete
              - run: npm install
          build-server:
            description: "Build server"
            steps:
              - run: cd reactnd-contacts-server
              - run: npm run build
          build-ui:
            description: "Build server"
            steps:
              - run: cd reactnd-contacts-complete
              - run: npm run build
